branches:
  only:
    - master

language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - android-27
  - build-tools-26.0.2
install:
  - ./gradlew dependencies

script:
  - ./gradlew build
