branches:
  only:
    - master

language: android
jdk: oraclejdk7

android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - android-25
  - build-tools-25.0.0
install:
  - ./gradlew dependencies

script:
  - ./gradlew build
