branches:
  only:
    - master

language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - android-26
  - build-tools-26.0.1
install:
  - ./gradlew dependencies

script:
  - ./gradlew build
